export type Message = { id:string; conversation_id:string; sender_id:string; body:string|null; media_url:string|null; reply_to_id:string|null; kind:string; metadata:Record<string,unknown>; created_at:string; deleted_at:string|null };
const API=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.replace(/\/$/,"")??"/api";
async function json<T>(r:Response):Promise<T>{const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(typeof b?.error==="string"?b.error:"api_request_failed");return b as T;}
export const listConversations=()=>fetch(API+"/me/conversations",{credentials:"include"}).then(r=>json(r));
export const createDM=(targetUserId:string)=>fetch(API+"/me/conversations/dm",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({targetUserId})}).then(r=>json<{conversationId:string}>(r));
export const createGroup=(memberIds:string[])=>fetch(API+"/me/conversations/group",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({memberIds})}).then(r=>json<{conversationId:string}>(r));
export const listMessages=(conversationId:string,before?:string)=>fetch(API+"/me/conversations/"+encodeURIComponent(conversationId)+"/messages?limit=50"+(before?"&before="+encodeURIComponent(before):""),{credentials:"include"}).then(r=>json<Message[]>(r));
export const sendMessage=(conversationId:string,input:{id?:string;body?:string|null;mediaUrl?:string|null;replyToId?:string|null;kind?:string;metadata?:Record<string,unknown>})=>fetch(API+"/me/conversations/"+encodeURIComponent(conversationId)+"/messages",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(input)}).then(r=>json<Message>(r));
export const markRead=(conversationId:string,messageId:string)=>fetch(API+"/me/conversations/"+encodeURIComponent(conversationId)+"/read",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({messageId})}).then(r=>json(r));
export const archiveConversation=(conversationId:string,archived:boolean)=>fetch(API+"/me/conversations/"+encodeURIComponent(conversationId),{method:"PATCH",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({archived})}).then(r=>json(r));
export function subscribeRealtime(conversationId:string,onMessage:(event:MessageEvent)=>void){const source=new EventSource(API+"/realtime?conversationId="+encodeURIComponent(conversationId),{withCredentials:true});source.addEventListener("message",onMessage);return ()=>source.close();}